### PR TITLE
Show invariant test results in the diff

### LINKED ISSUE #612: Show invariant test failures on UnicodeInvariantTest.txt
Having to run them locally to figure out what went wrong gets annoying (see https://github.com/unicode-org/unicodetools/pull/607#issuecomment-1808998728 but I have also been repeatedly annoyed) and takes time.

This can be done by making the GitHub workflow emit a `::error` line for each failure.

### PR DESCRIPTION
**Pull request by eggrobin**
See it in action [here](https://github.com/unicode-org/unicodetools/pull/646/commits/03b74f241ad1b7978773ca4d357c6a09c48ccd39#diff-c2f2f053bbaa14f43053e3fb81a8afd67add46a4be1377d3e411f0500b40dabf), I obviously don’t want to check in invariant test failures.

Split out from #645 since we will probably not merge that one before UTC-178. Fix #612.

### CODE REVIEW

File: unicodetools/src/main/java/org/unicode/text/UCD/TestUnicodeInvariants.java [hunk 1]
```diff
@@ -435,16 +437,26 @@ private static void equivalencesLine(String line, ParsePosition pp) throws Parse
             ++testFailureCount;
             printErrorLine("Test Failure", Side.START, testFailureCount);
         }
+        final List<String> errorMessage = new ArrayList<>();
```
Comment (markusicu) [inline unicodetools/src/main/java/org/unicode/text/UCD/TestUnicodeInvariants.java:440]: Nit/optional: It seems like a container should have a plural name. Maybe errorMessageLines?

**Review by markusicu — APPROVED** [review]
looks plausible

**Review by markusicu — APPROVED** [review]
tnx
